#
# Allows players with the 'skript.teleport' permission to be able to teleport
# with a compass like in WorldEdit.
#

#on rightclick with compass:
#	loop blocks above targeted block:
#		teleport player to loop-block 
#		stop trigger

#on rightclick with compass:
#    set {target} to targeted block
#    set {loc} to location of {target}
#    add 1 to {loc}'s y-coordinate
#    teleport player to {loc}
#    stop trigger